name: Unit tests
on: push
jobs:
  test:
    name: Tests without emulator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/gradle-build-action@v2

      - name: Run lint and unit tests
        run: ./gradlew --no-daemon app:lintOseDebug app:testGplayDebugUnitTest
      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            app/build/outputs/lint*
            app/build/reports
